version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 47chat-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./rag_store.faiss:/app/rag_store.faiss
      - ./rag_chunks.json:/app/rag_chunks.json
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 47chat-frontend
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_models:
    driver: local
